# Generated by Django 4.0.3 on 2022-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('store_id', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('customer_name', models.CharField(default='none', max_length=50)),
                ('order_total', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
