# Generated by Django 4.0.3 on 2022-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_order_razorpay_amount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='mainapp/images', null=True, upload_to='herbhouse/media/mainapp/images/'),
        ),
    ]
