# Generated by Django 4.0.3 on 2022-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='herbhouse/media/mainapp/images', null=True, upload_to='herbhouse/media/mainapp/images'),
        ),
    ]
