# Generated by Django 4.0.3 on 2022-05-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='mainapp/images/M1_1.png', null=True, upload_to='mainapp/images'),
        ),
    ]
